# Generated by Django 5.0 on 2025-12-18 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('missing_story', '실종 후기'), ('found_story', '발견 후기'), ('rescue_story', '구조 경험담'), ('tips', '꿀팁 공유'), ('lifecycle', '생애주기 경험')], help_text='카테고리', max_length=20)),
                ('title', models.CharField(help_text='제목', max_length=100)),
                ('content', models.TextField(help_text='내용')),
                ('images', models.JSONField(blank=True, default=list, help_text='사진 URL 배열 (최대 5장)')),
                ('views', models.IntegerField(default=0, help_text='조회수')),
                ('likes', models.IntegerField(default=0, help_text='좋아요 수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='작성자', on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '커뮤니티 게시글',
                'verbose_name_plural': '커뮤니티 게시글 목록',
                'db_table': 'communities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(help_text='게시글', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='communities.community')),
                ('user', models.ForeignKey(help_text='작성자', on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '커뮤니티 댓글',
                'verbose_name_plural': '커뮤니티 댓글 목록',
                'db_table': 'community_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['category', '-created_at'], name='communities_categor_cc0d1f_idx'),
        ),
    ]
