# Generated by Django 5.2.9 on 2025-12-23 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='likes',
        ),
        migrations.CreateModel(
            name='CommunityLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(help_text='게시글', on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='communities.community')),
                ('user', models.ForeignKey(help_text='사용자', on_delete=django.db.models.deletion.CASCADE, related_name='community_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '커뮤니티 좋아요',
                'verbose_name_plural': '커뮤니티 좋아요 목록',
                'db_table': 'community_likes',
                'indexes': [models.Index(fields=['community', 'user'], name='community_l_communi_d38fe6_idx')],
                'unique_together': {('community', 'user')},
            },
        ),
    ]
