# Generated by Django 5.0 on 2026-09-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_remove_community_likes_communitylike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='category',
            field=models.CharField(choices=[('free', '자유게시판'), ('found_story', '발견 후기'), ('rescue_story', '구조 경험담'), ('tips', '꿀팁 공유'), ('lifecycle', '생애주기 경험')], help_text='카테고리', max_length=20),
        ),
    ]
