# Generated by Django 5.2.17 on 2026-09-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_alter_community_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='메인 화면에 커뮤니티 카드를 노출할지 여부')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '커뮤니티 설정',
                'verbose_name_plural': '커뮤니티 설정',
                'db_table': 'community_settings',
            },
        ),
    ]
