# Generated by Django 5.2.9 on 2025-12-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, help_text='표시용 닉네임 (한글 가능)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='소셜 로그인 프로필 이미지 URL', max_length=500, null=True),
        ),
    ]
