# Generated by Django 5.2.9 on 2025-12-19 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_nickname_user_profile_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image_url',
        ),
    ]
