# Generated by Django 5.2.9 on 2025-12-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_nickname_remove_user_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, help_text='표시용 닉네임 (한글 가능)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='소셜 로그인 프로필 이미지 URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='프로필 사진 (업로드)', null=True, upload_to='profiles/'),
        ),
    ]
