# Generated by Django 5.0 on 2026-09-02 00:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_nickname_user_profile_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='연락처', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='전화번호 형식이 올바르지 않습니다. (예: 010-1234-5678)', regex='^01[016789]-\\d{3,4}-\\d{4}$')]),
        ),
    ]
