# Generated by Django 5.0 on 2026-09-02 05:46

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='프로필 사진 (업로드)', null=True, upload_to='profiles/', validators=[app.validators.validate_image_size]),
        ),
    ]
