# Generated by Django 5.2.17 on 2026-09-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_hospital_manager',
            field=models.BooleanField(default=False, help_text='병원 관리자 여부 (담당 병원/미용실만 관리 가능)'),
        ),
    ]
