# Generated by Django 5.2.17 on 2026-09-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_is_hospital_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hospital_manager_scope',
            field=models.CharField(choices=[('both', '병원+미용실'), ('hospital', '병원 전용'), ('grooming', '미용실 전용')], default='both', help_text='병원 관리자가 접근 가능한 범위 (병원 전용/미용실 전용/전체)', max_length=10),
        ),
    ]
