# Generated by Django 5.0 on 2025-12-18 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        ('missing_pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_report', '새 제보'), ('comment', '댓글'), ('resolved', '해결'), ('community', '커뮤니티')], help_text='알림 타입', max_length=20)),
                ('title', models.CharField(help_text='알림 제목', max_length=100)),
                ('message', models.TextField(help_text='알림 내용')),
                ('is_read', models.BooleanField(default=False, help_text='읽음 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(blank=True, help_text='관련 커뮤니티 글 (선택)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='communities.community')),
                ('missing_pet', models.ForeignKey(blank=True, help_text='관련 제보 (선택)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='missing_pets.missingpet')),
                ('user', models.ForeignKey(help_text='알림 받을 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림 목록',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_c4e471_idx')],
            },
        ),
    ]
