# Generated by Django 5.0 on 2026-09-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_report', '새 제보'), ('comment', '댓글'), ('resolved', '해결'), ('community', '커뮤니티'), ('like', '좋아요')], help_text='알림 타입', max_length=20),
        ),
    ]
