# Generated by Django 5.0 on 2025-12-18 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('adoption', '입양 준비'), ('puppy', '육아'), ('health', '건강관리'), ('senior', '노령 케어'), ('farewell', '이별/장례')], help_text='생애주기 단계', max_length=20, unique=True)),
                ('title', models.CharField(help_text='제목', max_length=100)),
                ('description', models.TextField(help_text='설명')),
                ('content', models.TextField(help_text='상세 내용')),
                ('checklist', models.JSONField(default=list, help_text='체크리스트 항목들')),
                ('image', models.ImageField(blank=True, help_text='대표 이미지', null=True, upload_to='lifecycles/')),
                ('order', models.IntegerField(default=0, help_text='표시 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '생애주기 가이드',
                'verbose_name_plural': '생애주기 가이드 목록',
                'db_table': 'lifecycle_guides',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='이름', max_length=50)),
                ('species', models.CharField(choices=[('dog', '강아지'), ('cat', '고양이'), ('other', '기타')], help_text='종류', max_length=10)),
                ('breed', models.CharField(blank=True, help_text='품종', max_length=50)),
                ('gender', models.CharField(choices=[('male', '수컷'), ('female', '암컷'), ('unknown', '모름')], default='unknown', help_text='성별', max_length=10)),
                ('birth_date', models.DateField(blank=True, help_text='생년월일', null=True)),
                ('adoption_date', models.DateField(blank=True, help_text='입양일', null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='몸무게 (kg)', max_digits=5, null=True)),
                ('profile_image', models.ImageField(blank=True, help_text='프로필 사진', null=True, upload_to='pets/')),
                ('notes', models.TextField(blank=True, help_text='특이사항 및 메모')),
                ('is_active', models.BooleanField(default=True, help_text='활성 상태 (무지개다리 건넜을 경우 False)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='보호자', on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '반려동물',
                'verbose_name_plural': '반려동물 목록',
                'db_table': 'pets',
                'ordering': ['-created_at'],
            },
        ),
    ]
