# Generated by Django 5.2.9 on 2025-12-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_neutered',
            field=models.BooleanField(default=False, help_text='중성화 여부'),
        ),
        migrations.AddField(
            model_name='pet',
            name='neutered_date',
            field=models.DateField(blank=True, help_text='중성화 수술일', null=True),
        ),
    ]
