# Generated by Django 5.2.9 on 2025-12-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycles', '0002_pet_is_neutered_pet_neutered_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lifecycleguide',
            options={'ordering': ['species', 'order'], 'verbose_name': '생애주기 가이드', 'verbose_name_plural': '생애주기 가이드 목록'},
        ),
        migrations.AddField(
            model_name='lifecycleguide',
            name='species',
            field=models.CharField(choices=[('dog', '강아지'), ('cat', '고양이'), ('other', '기타')], default='dog', help_text='반려동물 종류', max_length=10),
        ),
        migrations.AlterField(
            model_name='lifecycleguide',
            name='stage',
            field=models.CharField(choices=[('adoption', '입양 준비'), ('puppy', '육아'), ('health', '건강관리'), ('senior', '노령 케어'), ('farewell', '이별/장례')], help_text='생애주기 단계', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='lifecycleguide',
            unique_together={('species', 'stage')},
        ),
    ]
