# Generated by Django 5.2.9 on 2025-12-23 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycles', '0003_alter_lifecycleguide_options_lifecycleguide_species_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChecklistProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_item', models.CharField(help_text='체크리스트 항목 내용', max_length=500)),
                ('is_completed', models.BooleanField(default=False, help_text='완료 여부')),
                ('completed_at', models.DateTimeField(blank=True, help_text='완료 시간', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guide', models.ForeignKey(help_text='가이드', on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='lifecycles.lifecycleguide')),
                ('user', models.ForeignKey(help_text='사용자', on_delete=django.db.models.deletion.CASCADE, related_name='checklist_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 체크리스트 진행상황',
                'verbose_name_plural': '사용자 체크리스트 진행상황 목록',
                'db_table': 'user_checklist_progress',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'guide', 'checklist_item')},
            },
        ),
    ]
