# Generated by Django 5.2.9 on 2025-12-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycles', '0004_userchecklistprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='birth_date_unknown',
            field=models.BooleanField(default=False, help_text='생년월일 모름 여부'),
        ),
    ]
