# Generated by Django 5.0 on 2026-09-01 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycles', '0005_pet_birth_date_unknown'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(help_text='기록일')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='체중 (kg)', max_digits=5, null=True)),
                ('condition', models.CharField(choices=[('excellent', '매우 좋음'), ('good', '좋음'), ('normal', '보통'), ('poor', '안좋음'), ('sick', '아픔')], default='normal', help_text='건강 상태', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='특이사항')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(help_text='반려동물', on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='lifecycles.pet')),
            ],
            options={
                'verbose_name': '건강기록',
                'verbose_name_plural': '건강기록 목록',
                'db_table': 'pet_health_records',
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='PetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='사진', upload_to='pet_photos/')),
                ('caption', models.CharField(blank=True, help_text='사진 설명', max_length=200)),
                ('taken_date', models.DateField(blank=True, help_text='촬영일', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(help_text='반려동물', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='lifecycles.pet')),
            ],
            options={
                'verbose_name': '펫 사진',
                'verbose_name_plural': '펫 사진 목록',
                'db_table': 'pet_photos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_type', models.CharField(choices=[('dhppl', 'DHPPL (종합백신)'), ('rabies', '광견병'), ('corona', '코로나장염'), ('kennel_cough', '켄넬코프'), ('fvrcp', 'FVRCP (고양이 종합)'), ('felv', '고양이 백혈병'), ('other', '기타')], help_text='백신 종류', max_length=20)),
                ('vaccine_name', models.CharField(blank=True, help_text='백신명 (상세)', max_length=100)),
                ('vaccination_date', models.DateField(help_text='접종일')),
                ('next_due_date', models.DateField(blank=True, help_text='다음 접종 예정일', null=True)),
                ('hospital_name', models.CharField(blank=True, help_text='접종 병원', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='메모')),
                ('reminder_sent', models.BooleanField(default=False, help_text='알림 발송 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(help_text='반려동물', on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='lifecycles.pet')),
            ],
            options={
                'verbose_name': '예방접종',
                'verbose_name_plural': '예방접종 목록',
                'db_table': 'pet_vaccinations',
                'ordering': ['-vaccination_date'],
            },
        ),
    ]
