# Generated by Django 5.0 on 2026-09-02 05:46

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycles', '0006_healthrecord_petphoto_vaccination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifecycleguide',
            name='image',
            field=models.ImageField(blank=True, help_text='대표 이미지', null=True, upload_to='lifecycles/', validators=[app.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='프로필 사진', null=True, upload_to='pets/', validators=[app.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='petphoto',
            name='image',
            field=models.ImageField(help_text='사진', upload_to='pet_photos/', validators=[app.validators.validate_image_size]),
        ),
    ]
