# Generated by Django 5.0 on 2026-09-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycles', '0007_alter_lifecycleguide_image_alter_pet_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lifecycleguide',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='lifecycleguide',
            constraint=models.UniqueConstraint(condition=models.Q(('species__in', ['dog', 'cat'])), fields=('species', 'stage'), name='unique_species_stage_for_dog_cat'),
        ),
    ]
