# Generated by Django 5.0 on 2026-09-02 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycles', '0008_alter_lifecycleguide_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifecycleguide',
            name='custom_species_name',
            field=models.CharField(blank=True, help_text="종류가 '기타'일 때 구체적인 이름 (예: 도마뱀, 햄스터)", max_length=30),
        ),
        migrations.AlterField(
            model_name='lifecycleguide',
            name='order',
            field=models.IntegerField(default=1, help_text='표시 순서 (1 이상)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
