# Generated by Django 5.0 on 2026-09-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycles', '0009_lifecycleguide_custom_species_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifecycleguide',
            name='emoji',
            field=models.CharField(blank=True, default='🐾', help_text='탭/목록에 표시할 이모지', max_length=10),
        ),
    ]
