# Generated by Django 5.0 on 2025-12-18 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('missing', '실종'), ('found', '발견'), ('rescue', '구조')], help_text='카테고리 (실종/발견/구조)', max_length=10)),
                ('status', models.CharField(choices=[('active', '진행중'), ('resolved', '해결'), ('closed', '종료')], default='active', help_text='상태 (진행중/해결/종료)', max_length=10)),
                ('species', models.CharField(choices=[('dog', '강아지'), ('cat', '고양이'), ('other', '기타')], help_text='종류 (강아지/고양이/기타)', max_length=10)),
                ('breed', models.CharField(blank=True, help_text='품종', max_length=50)),
                ('name', models.CharField(blank=True, help_text='이름 (선택)', max_length=50)),
                ('description', models.TextField(help_text='특징 및 상세 설명')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='발생/발견 위치 위도', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='발생/발견 위치 경도', max_digits=9)),
                ('address', models.CharField(blank=True, help_text='주소', max_length=200)),
                ('occurred_at', models.DateTimeField(help_text='발생/발견 시간')),
                ('contact', models.CharField(help_text='연락처', max_length=100)),
                ('images', models.JSONField(default=list, help_text='사진 URL 배열 (최대 5장)')),
                ('views', models.IntegerField(default=0, help_text='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='제보자', on_delete=django.db.models.deletion.CASCADE, related_name='missing_pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '실종/발견/구조 제보',
                'verbose_name_plural': '실종/발견/구조 제보 목록',
                'db_table': 'missing_pets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='작성자', on_delete=django.db.models.deletion.CASCADE, related_name='missing_pet_comments', to=settings.AUTH_USER_MODEL)),
                ('missing_pet', models.ForeignKey(help_text='제보', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='missing_pets.missingpet')),
            ],
            options={
                'verbose_name': '제보 댓글',
                'verbose_name_plural': '제보 댓글 목록',
                'db_table': 'missing_pet_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='missingpet',
            index=models.Index(fields=['category', 'status'], name='missing_pet_categor_ae65cb_idx'),
        ),
        migrations.AddIndex(
            model_name='missingpet',
            index=models.Index(fields=['latitude', 'longitude'], name='missing_pet_latitud_8f19f2_idx'),
        ),
        migrations.AddIndex(
            model_name='missingpet',
            index=models.Index(fields=['-created_at'], name='missing_pet_created_eca0df_idx'),
        ),
    ]
