# Generated by Django 5.2.9 on 2025-12-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingpet',
            name='latitude',
            field=models.DecimalField(decimal_places=6, help_text='발생/발견 위치 위도', max_digits=10),
        ),
        migrations.AlterField(
            model_name='missingpet',
            name='longitude',
            field=models.DecimalField(decimal_places=6, help_text='발생/발견 위치 경도', max_digits=10),
        ),
    ]
