# Generated by Django 5.2.9 on 2025-12-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_pets', '0004_alter_missingpet_latitude_alter_missingpet_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingpet',
            name='latitude',
            field=models.DecimalField(decimal_places=15, help_text='발생/발견 위치 위도', max_digits=18),
        ),
        migrations.AlterField(
            model_name='missingpet',
            name='longitude',
            field=models.DecimalField(decimal_places=15, help_text='발생/발견 위치 경도', max_digits=18),
        ),
    ]
