# Generated by Django 5.0 on 2026-09-02 00:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_pets', '0005_alter_missingpet_latitude_alter_missingpet_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingpet',
            name='contact',
            field=models.CharField(help_text='연락처', max_length=100, validators=[django.core.validators.RegexValidator(message='전화번호 형식이 올바르지 않습니다. (예: 010-1234-5678)', regex='^01[016789]-\\d{3,4}-\\d{4}$')]),
        ),
    ]
