# Generated by Django 5.0 on 2025-12-18 00:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lifecycles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hospital', '동물병원'), ('grooming', '미용실')], help_text='종류 (병원/미용실)', max_length=10)),
                ('name', models.CharField(help_text='이름', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='위도', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='경도', max_digits=9)),
                ('address', models.CharField(help_text='주소', max_length=200)),
                ('phone', models.CharField(help_text='전화번호', max_length=20)),
                ('opening_hours', models.JSONField(blank=True, default=dict, help_text='영업시간 (JSON)')),
                ('services', models.JSONField(blank=True, default=list, help_text='제공 서비스 목록')),
                ('price_range', models.CharField(choices=[('free', '무료'), ('low', '저가'), ('medium', '일반'), ('high', '고가')], default='medium', help_text='가격대', max_length=10)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='평점 (0.00~5.00)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('review_count', models.IntegerField(default=0, help_text='리뷰 개수')),
                ('description', models.TextField(blank=True, help_text='설명')),
                ('website', models.URLField(blank=True, help_text='웹사이트')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '병원/미용실',
                'verbose_name_plural': '병원/미용실 목록',
                'db_table': 'hospitals',
                'ordering': ['-rating', 'name'],
                'indexes': [models.Index(fields=['type', '-rating'], name='hospitals_type_4c1847_idx'), models.Index(fields=['latitude', 'longitude'], name='hospitals_latitud_0ad327_idx')],
            },
        ),
        migrations.CreateModel(
            name='HospitalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='평점 (1~5점)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('content', models.TextField(help_text='후기 내용')),
                ('images', models.JSONField(blank=True, default=list, help_text='사진 URL 배열')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(help_text='병원/미용실', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hospitals.hospital')),
                ('user', models.ForeignKey(help_text='작성자', on_delete=django.db.models.deletion.CASCADE, related_name='hospital_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '병원/미용실 후기',
                'verbose_name_plural': '병원/미용실 후기 목록',
                'db_table': 'hospital_reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hospital', '-created_at'], name='hospital_re_hospita_afeaf3_idx')],
                'unique_together': {('user', 'hospital')},
            },
        ),
        migrations.CreateModel(
            name='HospitalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(help_text='방문 날짜')),
                ('purpose', models.CharField(help_text='방문 목적 (예방접종, 검진, 미용 등)', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='메모')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='비용', max_digits=10, null=True)),
                ('next_visit_date', models.DateField(blank=True, help_text='다음 방문 예정일', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(help_text='병원/미용실', on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='hospitals.hospital')),
                ('pet', models.ForeignKey(help_text='반려동물', on_delete=django.db.models.deletion.CASCADE, related_name='hospital_visits', to='lifecycles.pet')),
                ('user', models.ForeignKey(help_text='사용자', on_delete=django.db.models.deletion.CASCADE, related_name='hospital_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '방문 기록',
                'verbose_name_plural': '방문 기록 목록',
                'db_table': 'hospital_visits',
                'ordering': ['-visit_date'],
                'indexes': [models.Index(fields=['user', '-visit_date'], name='hospital_vi_user_id_73a214_idx'), models.Index(fields=['pet', '-visit_date'], name='hospital_vi_pet_id_3bae36_idx')],
            },
        ),
    ]
