# Generated by Django 5.2.9 on 2025-12-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_24_hours',
            field=models.BooleanField(default=False, help_text='24시간 운영 여부'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='opening_hours',
            field=models.JSONField(blank=True, default=dict, help_text="영업시간 (JSON) - 예: {'월': '09:00-18:00', '화': '09:00-18:00'}"),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['is_24_hours'], name='hospitals_is_24_h_167025_idx'),
        ),
    ]
