# Generated by Django 5.2.9 on 2025-12-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_hospital_is_24_hours_alter_hospital_opening_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='kakao_place_id',
            field=models.CharField(blank=True, help_text='카카오맵 장소 ID (중복 방지용)', max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['kakao_place_id'], name='hospitals_kakao_p_c0a07e_idx'),
        ),
    ]
