# Generated by Django 5.0 on 2026-09-02 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_hospital_kakao_place_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalvisit',
            name='hospital_address',
            field=models.CharField(blank=True, help_text='병원 주소 (직접 입력)', max_length=200),
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='hospital_name',
            field=models.CharField(blank=True, help_text='병원 이름 (직접 입력)', max_length=100),
        ),
        migrations.AddField(
            model_name='hospitalvisit',
            name='hospital_phone',
            field=models.CharField(blank=True, help_text='병원 전화번호 (직접 입력)', max_length=20),
        ),
        migrations.AlterField(
            model_name='hospitalvisit',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='병원/미용실 (선택)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='hospitals.hospital'),
        ),
    ]
