# Generated by Django 5.2.17 on 2026-09-03 04:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_hospitalvisit_hospital_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='이 병원/미용실을 담당하는 병원 관리자 목록', related_name='managed_hospitals', to=settings.AUTH_USER_MODEL),
        ),
    ]
