# Generated by Django 5.2.17 on 2026-09-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_hospital_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='사진 URL 배열 (첫 번째가 대표/썸네일 이미지, 최대 5장)'),
        ),
    ]
