# Generated by Django 5.2.17 on 2026-09-03 05:51

from django.db import migrations, models


def merge_low_high_into_medium(apps, schema_editor):
    """기존 저가/고가로 저장된 병원/미용실을 전부 일반(medium)으로 합침"""
    Hospital = apps.get_model('hospitals', 'Hospital')
    Hospital.objects.filter(price_range__in=['low', 'high']).update(price_range='medium')


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_hospital_images'),
    ]

    operations = [
        migrations.RunPython(merge_low_high_into_medium, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='hospital',
            name='price_range',
            field=models.CharField(choices=[('free', '무료'), ('medium', '일반')], default='medium', help_text='가격대', max_length=10),
        ),
    ]
